services:
  - type: web
    name: mh-expenses-app-frontend
    runtime: static
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html